### ISSUE TITLE
Tidal audio download hangs once "rescan folders"

### ISSUE THREAD

**Issue by steve1977** [RandomNinjaAtk/docker-lidarr-extended#70] opened 2022-09-18 00:48 UTC
I have Lidarr-extended configured to download audio files from tidal (video is disabled).

Everything runs flawless and I really like the script, big thanks!

However, things stop and idle out once the Lidarr "rescan folders" feature kicks in. Let me describe what I mean:

1) All download and import works well once starting the script

2) Once "rescan folders" auto-starts, the audio script stops (message in the log around Lidarr running other services and will pause the script until they complete)

3) The "rescan folders" takes more than 24-48 hours. Not sure whether it ever finishes. I never let it run more than 48 hours, so not sure it ever completes

4) I had a similar issue before that the "rescan folders" task takes forever and freezes Lidarr. However, this was when I had 10,000s of songs in "unidentified". After I changed this, "rescan folder" run quite quick

5) When I disable the script and run "rescan folder", all is good and it finishes quite quickly

6) My guess is that it is somehow related to Lidarr touching so many different artists (one single downloaded for each), but no clue why the scan works when I disable the script and just let it run "clean"

7) Unfortunately, Lidarr does not allow to disable the auto-scan and also not to change the interval

Let me know if helpful to send any form of logs and what you'd need for troubleshooting?

**Comment by RandomNinjaAtk** [comment] 2022-09-18 15:14
By design, this script pauses when Lidarr has tasks its performing... So what your experiencing is normal....

**Comment by steve1977** [comment] 2022-09-18 17:15
The issue is that the "scanning" is taking forever (24+ hours). There seems to be something done by the script that leads to the "music scan" working the same way as it does when scanning a completely new library.

**Comment by steve1977** [comment] 2022-09-18 23:56
It clearly has something to do with the script:

Disable script: Start Lidarr and run "rescan folder" manually. Completed after 2 minutes

Enable script: Restart Lidarr and run "rescan folder" manually. Still not completed after 36 hours.

**Comment by steve1977** [comment] 2022-09-19 01:40
I did some more troubleshooting to isolate the issue. It is replicable:

Disable script: "Rescan folder" completes in 1-2min

Enable video script: "Rescan folder" completes in 1-2min

Enable audio script (before tidal search starts): "Rescan folder" completes in 1-2min

Enable audio script (once tidal search starts): Script pauses, but "rescan folder" takes hours or days to complete (I let it run for up to 48 hours and still did not complete)

This is replicate on my end, so let me know if anything I can provide. Thanks!

**Comment by RandomNinjaAtk** [comment] 2022-09-21 14:17
Interesting, I don't really have any insight into how that process works to understand what could be triggering the extra processing time.... A quick thought though, disable the "MetadataPostProcess.bash" under Lidarr -> Settings -> Connections and see if that helps...

**Comment by steve1977** [comment] 2022-09-24 15:32
Let me try. It was set only for "on track retag". I have now disabled and see how this works.

**Comment by steve1977** [comment] 2022-09-25 08:22
Unfortunately, this does not make a difference.

Maybe the issue is somewhat related to my music library being on the unraid array?

**Comment by Yosh82** [comment] 2022-09-25 09:57
I've not had this issue with the tidal script at all, I have around 900 artists and 100k files so far with the script.

Have you checked permissions on the share that LE is using? It sounds like a permissions issue, maybe the script is trying to rename / write meta data to the tracks on scan and fails and hangs?

Must be a local issue, I've had mine running for a week now and never had the issue. Just run a scan which took a few mins as expected.

What do the docker logs say when it's hanging? Is it trying to access anything?

**Comment by steve1977** [comment] 2022-09-25 10:41
Thanks. This reads intuitively right. Maybe both LE and the script access the file at the same time and some permission issue stops things? Technically, the script is paused, but it may pause too late, so it causes LE to hang.

From what I remember, the logs shows actual folder scanning. A "complete rescan" may take a week due to the size of my library. Instead of just rescanning new files.

What's odd though is that restarting the docker solves and the rescan completes in 1-2 minutes. And then the script works for 24 yours.

I checked about permissions. LE is set to "set permissions = yes" and "chmod 777" and "chown abc".

**Comment by Yosh82** [comment] 2022-09-25 11:21
If that doesn't work, I'd suggest creating a new test share, set LE to use that and see how that goes. It does sound permissions related, and now you mentioned the abc account, I'm sure I had a similar issue once I replaced a cache disk for tdarr before, although the share permissions were correct, the docker logs showed access denied. Recreating the share fixed it.

Thought I'd share the info as may prove helpful, even just for troubleshooting.

Luckily, mine is working flawlessly, thanks again all involved in the release :)

**Comment by steve1977** [comment] 2022-09-25 11:26
Let me fix the permissions. You also have LE set as abc?

**Comment by Yosh82** [comment] 2022-09-25 11:31
The Share LE uses for media (I also use a cache disk for downloads and permissions are the same):

  |   | Parent Directory |  
  |   | _toimport | username | **drwxrwxrwx** | <FOLDER> | 2022-09-22 22:33 | disk5 | ...
  |   | Albums | username | **drwxrwxrwx** | <FOLDER> | 2022-09-25 10:07 | disk5 | ...
  |   | bin | root | **drwxrwxrwx** | <FOLDER> | 2022-09-25 12:01 | disk5 | ...
  |   | Music-Videos | username | **drwxrwxrwx** | <FOLDER> | 2022-09-24 09:22 | disk5
  
  Good luck

**Comment by steve1977** [comment] 2022-09-25 11:55
Ah... I think I understand where my issue may be... My download directory is not on the same drive. Looks like your is?

**Comment by Yosh82** [comment] 2022-09-25 12:00
No, my download directory is on a cache drive, so it downloads to that, then once LE renamer kicks it, it does the moves to the Albums folder.

I did think it had the same permissions as above which it doesn't. My downloads cache share uses the following permissions, note the owner is root, so I may have set the path in LE which it then created the dir, rather than a manual creation (my memory is terrible but I think I let LE create the dir rather than a manual creation then point LE at it):

  |   | Parent Directory |  
  |   | lidarr-downloads | root | drwxr-xr-x | <FOLDER> | 2022-09-24 12:12 |
  |   | temp | username | drwxrwxrwx | <FOLDER> | 2022-09-25 09:56 |

**Comment by Yosh82** [comment] 2022-09-25 12:21
For clarity, as the original issue is folder rescan hanging, I'd aim to fix that first. It may not be related to the downloads path, unless it's trying to move / rename then and missing permissions.

Check permissions are correct, or check the docker log. This is what it looks like for me / when it's working. If it was permissions errors, I'd expect to see an error in the log.

![image](https://user-images.githubusercontent.com/106485860/192143072-eb80add6-e383-4842-a703-9614aae4df0d.png)

**Comment by steve1977** [comment] 2022-09-26 03:54
The issue seems to be that it is doing a full rescan although, which may well take a full week or so given the size of my library. When I do the scan with the script disabled, it scans successfully (but I guess only rescans changed files?). Have a look below from the docker log, while scanning (while the script is paused). Nothing of Ariana Grande was changed nor added.

[Info] RssSyncService: Starting RSS Sync 
[Warn] FetchAndParseRssService: No available indexers. check your configuration. 
[Info] DownloadDecisionMaker: No results found 
[Info] RssSyncService: RSS Sync Completed. Reports found: 0, Reports grabbed: 0 
[Info] ExistingMetadataImporter: Found 75 existing metadata files 
[Info] ExistingLyricImporter: Found 0 existing lyric files 
[Info] ExistingOtherExtraImporter: Found 0 existing other extra files 
[Info] ExistingExtraFileService: Found 0 extra files 
[Info] DiskScanService: Completed scanning disk for Ariana Grande

**Comment by Bait-Fish** [comment] 2022-10-04 00:44
My LE does a 13 hour duration rescan every 24 hours. This on a 28k artist/47k album/467k track library. Extended Audio finds 55k missing and cutoff. While the rescan progresses, EA pauses. EV continues, finshes, restarts, repeat. Seems inefficient for EA to wait sooo long. Especially as it's the part I care more for.

During the now 13 hour daily scan, I see similar logging immediately above, not just for Ariana ;)

I haven't tried any troubleshooting. I figured it was just due to the extensive autoconfig defaults combined with library size.

I also have a vanilla (latest) lidarr container that looks at the same library. Its daily rescan is a very small fraction of time (when I run that container. LE has taken its place).

Not sure what else I can add. steve1977 seems to have been quite thorough.

**Comment by RandomNinjaAtk** [comment] 2022-10-04 01:00
Update to the latest, re-run autoconfig, see if it improves. To re-run autoconfig, you need to delete the autoconfig log file in /config/extended/logs/ folder

**Comment by Bait-Fish** [comment] 2022-10-04 01:04
Will do. Thanks for the prompt response.

**Comment by RandomNinjaAtk** [comment] 2022-10-04 01:06
I think the latest permissions tweaks may have helped. But without testing, hard to know...

**Comment by Bait-Fish** [comment] 2022-10-05 01:00
For me, no change. Rescan >13 hours today starting at 4 am and still going.

**Comment by RandomNinjaAtk** [comment] 2022-10-05 01:14
Hmm my scans are only taking 3 min, but my library is only around 100k tracks. I did perform a permissions reset via unraid docker safe permissions option. Before the change it was taking a long time...

**Comment by RandomNinjaAtk** [comment] 2022-10-16 13:25
So I was previously seeing this issue in my personal setup, but it seems to have been eradicated with the recent changes. I cannot reproduce it at this point. If your still having an issue, its likely a permissions issue. I'm closing this because there is no further actions that I can tell are needed.

**Closed by RandomNinjaAtk** 2022-10-16 13:25 UTC

**Comment by steve1977** [comment] 2022-11-19 01:45
Unfortunately, I am still experiencing the same issue. Once "rescan folders" kicks in, it rescans all folders although only a few albums were added. This is not the case when I disable the script. Any thoughts?
