### ISSUE TITLE
Compilation Album Unsuccessful, Numbered Versions Downloaded, Audio Script Hangs

### ISSUE THREAD

**Issue by Bait-Fish** [RandomNinjaAtk/docker-lidarr-extended#136] opened 2022-11-23 16:42 UTC
**Describe the bug**

With album named "Relaxing Bossa Lounge" monitored in Lidarr-Extended, Audio script v1.0.292 did not download that specific album. Many numbered variations of Relaxing Bossa Lounge XX successfully downloaded. No version of Relaxing Bossa Lounge imported to LE.

Audio script eventually stopped functioning. Found script hung/not functioning the following day. 

**To Reproduce**

Container setting "enableVideoScript" set to "false", with "Relaxing Bossa Lounge" already monitored in Lidarr-Extended (2008 compilation)

**Expected behavior**
Expected to download a single album

**Log Data**
https://pastebin.com/K6WJdtsx
Note, middle of the log removed due to Pastebin size limitation

**Docker Info:**
 - Docker Version: 20.10.18 (Unraid Version: 6.11.3)
 - Extended Script Version: 292

**Additional context**

This issue did not present when container setting "enableVideoScript" to "true". Suspect the video script caused 'waiting for video download' bypassed the album in that case

**Comment by RandomNinjaAtk** [comment] 2022-11-23 17:50
Just because something is downloaded, does not guarantee a successful import, since it's up to lidarr to make the final decision...

Also what your seeing is expected behavior, if you want to resolve it, you should update musicbrainz with a link for the album:
https://github.com/RandomNinjaAtk/docker-lidarr-extended/wiki/Extended-Audio-Script-Information#q-it-cannot-find-albums-that-i-know-should-be-available

**Comment by RandomNinjaAtk** [comment] 2022-11-23 19:29
Your additional context note should be fixed in 1.0.296

**Comment by Bait-Fish** [comment] 2022-11-23 19:31
Thanks. Will check.

**Comment by Bait-Fish** [comment] 2022-11-28 20:03
I have not been able to check this while focused on other troubleshooting.

**Comment by RandomNinjaAtk** [comment] 2022-12-15 13:06
@Bait-Fish Is this resolved?

**Comment by RandomNinjaAtk** [comment] 2022-12-29 13:34
Closing due to lack of feedback, please open a new issue if still having a problem...

**Closed by RandomNinjaAtk** 2022-12-29 13:34 UTC
Labels: bug
